/* Generated By:JJTree: Do not edit this line. ASTarray.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTarray extends SimpleNode {
    public ASTarray(int id) {
        super(id);
    }

    public ASTarray(JmmParser p, int id) {
        super(p, id);
    }

    public void applySemanticAnalysis(SymbolTable table) {
        SimpleNode var = ((SimpleNode) children[0]);
        SimpleNode access = ((SimpleNode) children[1]);
        if (var.name != null) {
            Symbol s = table.getSymbol(var.name);
            if (s != null) {
                if (!s.getType().equals("int[]")) {
                    System.out.println("Variable not of type int[] on line " + line);
                    System.exit(0);
                }

                if (!s.isInitialized()) {
                    System.out.println("Array not initialized on line " + line);
                    System.exit(0);
                }

                access.applySemanticAnalysis(table);
                return;
            }

            System.out.println(var.name + " isn't a known variable on line " + line);
            System.exit(0);
        }
    }
}
/* JavaCC - OriginalChecksum=1a86f515b68517bf53dbce8ad90edbd1 (do not edit this line) */
