/* Generated By:JJTree: Do not edit this line. ASTADDSUB.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTADDSUB extends SimpleNode {
  public ASTADDSUB(int id) {
    super(id);
  }

  public ASTADDSUB(JmmParser p, int id) {
    super(p, id);
  }

  public String toString(String prefix) {
    this.print = this.name;
    return prefix + this.print;
  }

}
/* JavaCC - OriginalChecksum=44acf13761db8f3aed84c23f5034a2e5 (do not edit this line) */
