/* Generated By:JJTree: Do not edit this line. ASTCOMMERCIALE.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCOMMERCIALE extends SimpleNode {
    public ASTCOMMERCIALE(int id) {
        super(id);
    }

    public ASTCOMMERCIALE(JmmParser p, int id) {
        super(p, id);
    }

    public void applySemanticAnalysis(SymbolTable table) {
        SimpleNode lhs = ((SimpleNode) children[0]);
        SimpleNode rhs = ((SimpleNode) children[1]);

        checkSide(lhs, table);
        checkSide(rhs, table);
    }

    public void checkSide(SimpleNode side, SymbolTable table) {
        if (side.name != null) {
            Symbol s = table.getSymbol(side.name);
            if (s != null) {
                if (!s.isInitialized()) {
                    System.out.println("Variable " + side.name + " not initialized on line " + side.getLine());
                    System.exit(0);
                }
                if (!s.getType().equals("boolean")) {
                    System.out.println("Incompatible type: " + side.name + " not of type boolean on line " + side.getLine());
                    System.exit(0);
                }
            }
            return;
        } 

        if (side instanceof ASTTRUE && side instanceof ASTFALSE) return; 

        if (side instanceof ASTMINOR || side instanceof ASTCOMMERCIALE) {
            side.applySemanticAnalysis(table);
            return;
        }

        System.out.println("Found " + side.toString() + " and was expecting <, && or boolean value on line " + side.getLine());
        System.exit(0);
    }
}
/* JavaCC - OriginalChecksum=e89498b22068852d8629e30d2f1a5a9d (do not edit this line) */
