/* Generated By:JJTree: Do not edit this line. ASTCOMMERCIALE.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCOMMERCIALE extends SimpleNode {
    public ASTCOMMERCIALE(int id) {
        super(id);
    }

    public ASTCOMMERCIALE(JmmParser p, int id) {
        super(p, id);
    }

    public void applySemanticAnalysis(SymbolTable table) {
        if (children == null) return;

        for (int i = 0; i < children.length; i++) {
            ((SimpleNode) children[i]).applySemanticAnalysis(table);
        }
    }
}
/* JavaCC - OriginalChecksum=e89498b22068852d8629e30d2f1a5a9d (do not edit this line) */
