/* Generated By:JJTree: Do not edit this line. ASTINTEGER.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTINTEGER extends SimpleNode {
    public ASTINTEGER(int id) {
        super(id);
    }

    public ASTINTEGER(JmmParser p, int id) {
        super(p, id);
    }

    public String toString(String prefix) {
        return prefix + this.name;
    }
}
/* JavaCC - OriginalChecksum=3dced66d0f48cf59762f690585e3f853 (do not edit this line) */
