/* Generated By:JJTree: Do not edit this line. ASTIDENTIFIER.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTIDENTIFIER extends SimpleNode {
    public ASTIDENTIFIER(int id) {
        super(id);
    }

    public ASTIDENTIFIER(JmmParser p, int id) {
        super(p, id);
    }

    public String toString(String prefix) {
        return prefix + this.name;
    }
}
/* JavaCC - OriginalChecksum=95c83ca56f05760c5fba6e61046ce3de (do not edit this line) */
