/* Generated By:JJTree: Do not edit this line. ASTMINOR.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMINOR extends BinaryOperator {
    public ASTMINOR(int id) {
        super(id);
    }

    public ASTMINOR(JmmParser p, int id) {
        super(p, id);
    }
}
/* JavaCC - OriginalChecksum=3b9504027d588967d242165cbdf7818a (do not edit this line) */
