/* Generated By:JJTree: Do not edit this line. ASTMINOR.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMINOR extends SimpleNode {
    public ASTMINOR(int id) {
        super(id);
    }

    public ASTMINOR(JmmParser p, int id) {
        super(p, id);
    }

    public void applySemanticAnalysis(SymbolTable table) {
        SimpleNode lhs = ((SimpleNode) children[0]);
        SimpleNode rhs = ((SimpleNode) children[1]);

        checkSide(lhs, table);
        checkSide(rhs, table);
    }

    public void checkSide(SimpleNode side, SymbolTable table) {
        if (side.name != null) {
            if (side instanceof ASTADDSUB || side instanceof ASTMULDIV) {
                side.applySemanticAnalysis(table);
                return;
            }

            Symbol s = table.getSymbol(side.name);
            if (s != null) {
                if (!s.isInitialized()) {
                    System.out.println("Variable " + side.name + " not initialized on line " + side.getLine());
                    System.exit(0);
                }
                if (!s.getType().equals("int")) {
                    System.out.println("Incompatible type: " + side.name + " not of type int on line " + side.getLine());
                    System.exit(0);
                }
                return;
            }

            try { 
                Integer.parseInt(side.name); 
            } catch(NumberFormatException | NullPointerException e) { 
                System.out.println("Incompatible type: " + side.name + " not of type int on line " + side.getLine());
                System.exit(0);
            }

            return;
        }

        if (side instanceof ASTarray) {
            side.applySemanticAnalysis(table);
        }

        System.out.println("Found " + side.toString() + " and was expecting *, /, +, -, or integer value on line " + side.getLine());
        System.exit(0);
    }
}
/* JavaCC - OriginalChecksum=3b9504027d588967d242165cbdf7818a (do not edit this line) */
