/* Generated By:JJTree: Do not edit this line. ASTmainDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTmainDeclaration extends SimpleNode {
    public ASTmainDeclaration(int id) {
        super(id);
    }

    public ASTmainDeclaration(JmmParser p, int id) {
        super(p, id);
    }

    public void createSymbolTable(SymbolTable table) {
        SymbolTable methodTable = new SymbolTable(table);
        JmmParser.getInstance().addMethod("main", methodTable);

        if (children == null) return;

        for (int i = 0; i < children.length; i++) {
            ((SimpleNode) children[i]).createSymbolTable(methodTable);
        }
    }

    public void applySemanticAnalysis(SymbolTable table) {
        SymbolTable methodTable = JmmParser.getInstance().getMethods().get("main");

        if (children == null) return;

        for (int i = 0; i < children.length; i++) {
            ((SimpleNode) children[i]).applySemanticAnalysis(methodTable);
        }
    }
}
/* JavaCC - OriginalChecksum=59d099a20c7981074565a2963bda3c54 (do not edit this line) */
