/* Generated By:JJTree: Do not edit this line. ASTMULDIV.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMULDIV extends BinaryOperator {
  public ASTMULDIV(int id) {
    super(id);
  }

  public ASTMULDIV(JmmParser p, int id) {
    super(p, id);
  }

  public String toString(String prefix) {
      this.print = this.name;
      return prefix + this.print;
  }

}
/* JavaCC - OriginalChecksum=dba21152cb2b31c492242c702c5501d8 (do not edit this line) */
