/* Generated By:JJTree: Do not edit this line. ASTvarDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTvarDeclaration extends SimpleNode {
    public ASTvarDeclaration(int id) {
        super(id);
    }

    public ASTvarDeclaration(JmmParser p, int id) {
        super(p, id);
    }

    public void createSymbolTable(SymbolTable table) {
        Symbol.Access access;
        String type;

        if (table.getParent() == null) 
            access = Symbol.Access.global;
        else
            access = Symbol.Access.local;

        if (children.length == 2 && ((SimpleNode)children[0]).index != -1)
            type = JmmParserConstants.tokenImage[((SimpleNode)children[0]).index].replaceAll("\"", "");
        else if (children.length == 2)
            type = ((SimpleNode)children[0]).name;
        else
            type = "int[]";

        Symbol symbol = new Symbol(type, ((SimpleNode)children[children.length-1]).name, access);
        table.addSymbol(symbol);
    }
}
/* JavaCC - OriginalChecksum=fc6be33fb0f0acf5f47d8d6fb07f2652 (do not edit this line) */
