/* Generated By:JJTree&JavaCC: Do not edit this line. JmmParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JmmParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 9;
  /** RegularExpression Id. */
  int CLASS = 10;
  /** RegularExpression Id. */
  int EXTENDS = 11;
  /** RegularExpression Id. */
  int LEFTBRACKET = 12;
  /** RegularExpression Id. */
  int RIGHTBRACKET = 13;
  /** RegularExpression Id. */
  int LEFTPARENTHESES = 14;
  /** RegularExpression Id. */
  int RIGHTPARENTHESES = 15;
  /** RegularExpression Id. */
  int LEFTSQUAREBRACKET = 16;
  /** RegularExpression Id. */
  int RIGHTSQUAREBRACKET = 17;
  /** RegularExpression Id. */
  int INT = 18;
  /** RegularExpression Id. */
  int BOOLEAN = 19;
  /** RegularExpression Id. */
  int STRINGARRAY = 20;
  /** RegularExpression Id. */
  int VOID = 21;
  /** RegularExpression Id. */
  int COLON = 22;
  /** RegularExpression Id. */
  int DOT = 23;
  /** RegularExpression Id. */
  int SEMICOLON = 24;
  /** RegularExpression Id. */
  int PUBLIC = 25;
  /** RegularExpression Id. */
  int STATIC = 26;
  /** RegularExpression Id. */
  int MAIN = 27;
  /** RegularExpression Id. */
  int IF = 28;
  /** RegularExpression Id. */
  int ELSE = 29;
  /** RegularExpression Id. */
  int WHILE = 30;
  /** RegularExpression Id. */
  int RETURN = 31;
  /** RegularExpression Id. */
  int EQUALS = 32;
  /** RegularExpression Id. */
  int COMMERCIALE = 33;
  /** RegularExpression Id. */
  int MINOR = 34;
  /** RegularExpression Id. */
  int ADDSUB = 35;
  /** RegularExpression Id. */
  int MULDIV = 36;
  /** RegularExpression Id. */
  int LENGTH = 37;
  /** RegularExpression Id. */
  int TRUE = 38;
  /** RegularExpression Id. */
  int FALSE = 39;
  /** RegularExpression Id. */
  int THIS = 40;
  /** RegularExpression Id. */
  int NEW = 41;
  /** RegularExpression Id. */
  int EXCLAMATION = 42;
  /** RegularExpression Id. */
  int IDENTIFIER = 43;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int ML_COMMENT_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "<INTEGER>",
    "\"class\"",
    "\"extends\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"int\"",
    "\"boolean\"",
    "\"String[]\"",
    "\"void\"",
    "\",\"",
    "\".\"",
    "\";\"",
    "\"public\"",
    "\"static\"",
    "\"main\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"return\"",
    "\"=\"",
    "\"&&\"",
    "\"<\"",
    "<ADDSUB>",
    "<MULDIV>",
    "\"length\"",
    "\"true\"",
    "\"false\"",
    "\"this\"",
    "\"new\"",
    "\"!\"",
    "<IDENTIFIER>",
  };

}
