/* Generated By:JJTree: Do not edit this line. SimpleNode.java Version 6.0 */
/* JavaCCOptions:MULTI=false,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

public
class SimpleNode implements Node {

  protected Node parent;
  protected Node[] children;
  protected int id;
  protected Object value;
  protected JmmParser parser;

  public SimpleNode(int i) {
    id = i;
  }

  public SimpleNode(JmmParser p, int i) {
    this(i);
    parser = p;
  }

  public void jjtOpen() {
  }

  public void jjtClose() {
  }

  public void jjtSetParent(Node n) { parent = n; }
  public Node jjtGetParent() { return parent; }

  public void jjtAddChild(Node n, int i) {
    if (children == null) {
      children = new Node[i + 1];
    } else if (i >= children.length) {
      Node c[] = new Node[i + 1];
      System.arraycopy(children, 0, c, 0, children.length);
      children = c;
    }
    children[i] = n;
  }

  public Node jjtGetChild(int i) {
    return children[i];
  }

  public int jjtGetNumChildren() {
    return (children == null) ? 0 : children.length;
  }

  public void jjtSetValue(Object value) { this.value = value; }
  public Object jjtGetValue() { return value; }

  /* You can override these two methods in subclasses of SimpleNode to
     customize the way the node appears when the tree is dumped.  If
     your output uses more than one line you should override
     toString(String), otherwise overriding toString() is probably all
     you need to do. */

  public String toString() {
    int index = 0;

    switch(JmmParserTreeConstants.jjtNodeName[id]){
      case "INTEGER":
        index = 5; break;
      case "CLASS":
        index = 6; break;
      case "EXTENDS":
        index = 7; break;
      case "LEFTBRACKET":
        index = 8; break;
      case "RIGHTBRACKET":
        index = 9; break;
      case "LEFTPARENTHESES":
        index = 10; break;
      case "RIGHTPARENTHESES":
        index = 11; break;
      case "LEFTSQUAREBRACKET":
        index = 12; break;
      case "RIGHTSQUAREBRACKET":
        index = 13; break;
      case "INT":
        index = 14; break;
      case "BOOLEAN":
        index = 15; break;
      case "STRINGARRAY":
        index = 16; break;
      case "VOID":
        index = 17; break;
      case "COLON":
        index = 18; break;
      case "DOT":
        index = 19; break;
      case "SEMICOLON":
        index = 20; break;
      case "PUBLIC":
        index = 21; break;
      case "STATIC":
        index = 22; break;
      case "MAIN":
        index = 23; break;
      case "IF":
        index = 24; break;
      case "ELSE":
        index = 25; break;
      case "WHILE":
        index = 26; break;
      case "RETURN":
        index = 27; break;
      case "EQUALS":
        index = 28; break;
      case "COMMERCIALE":
        index = 29; break;
      case "MINOR":
        index = 30; break;
      case "PLUS":
        index = 31; break;
      case "MINUS":
        index = 32; break;
      case "ASTERISC":
        index = 33; break;
      case "SLASH":
        index = 34; break;
      case "LENGTH":
        index = 35; break;
      case "TRUE":
        index = 36; break;
      case "FALSE":
        index = 37; break;
      case "THIS":
        index = 38; break;
      case "NEW":
        index = 39; break;
      case "EXCLAMATION":
        index = 40; break;
      case "IDENTIFIER":
        index = 41; break;
    }

    String print;

    if(index == 0)
      print = JmmParserTreeConstants.jjtNodeName[id];
    else 
      print = JmmParserConstants.tokenImage[index].replaceAll("\"","");

    return print;
  }
  public String toString(String prefix) { return prefix + toString(); }

  /* Override this method if you want to customize how the node dumps
     out its children. */

  public void dump(String prefix) {

      System.out.println(toString(prefix));

    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode)children[i];
        if (n != null) {
          n.dump(prefix + " ");
        }
      }
    }
  }

  public int getId() {
    return id;
  }
}

/* JavaCC - OriginalChecksum=2b7ec5aa5689d0e7377adde4da00c1d2 (do not edit this line) */
